# Generated by Django 5.0 on 2023-12-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_grade_class_grade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grade',
            new_name='Series',
        ),
    ]
