# Generated by Django 5.0 on 2023-12-20 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_modality_series_modality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='grade',
            new_name='series',
        ),
    ]
