# Generated by Django 5.0 on 2023-12-20 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_rename_grade_class_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.series'),
        ),
        migrations.AlterField(
            model_name='series',
            name='modality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='classes.modality'),
        ),
    ]
