# Generated by Django 5.0 on 2023-12-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='job_title',
            field=models.CharField(blank=True, choices=[('P', 'Professor'), ('C', 'Coordenador'), ('D', 'Diretor'), ('T', 'Técnico')], max_length=11, null=True),
        ),
    ]
